[tox]
min_version = 4
env_list =
    pre-commit,
    mypy-pkg,
    py3{9,10,11,12},
    coverage-report


[testenv]
package = wheel
wheel_build_env = .pkg
extras =
    tests
deps =
    coverage[toml]
commands =
    coverage run -m pytest {posargs}


[testenv:coverage-report]
description = Report coverage over all test runs.
deps = coverage[toml]>=5.0.2
skip_install = true
commands =
    coverage combine
    coverage report


[testenv:pre-commit]
description = Run all pre-commit hooks.
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files


[testenv:mypy-pkg]
description = Type-check the package.
extras = typing
commands = mypy src
