name: Build PyPI Package (and upload releases)

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"

      - name: Build package
        run: uv build

      - name: Save package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist

  release-pypi:
    name: Publish released package to pypi.org
    if: github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package

    steps:
      - name: Download built package artifacts
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
